services:
  - type: web
    name: water-pollution-detector
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn app:app
    autoDeploy: true




